# - name: apt install gnupg
#   apt:
#     name: 
#       - ca-certificates
#       - curl
#       - gnupg
#       - lsb-release
#       - ubuntu-keyring
#     state: present
#     update_cache: yes

# - name: Add nginx GPG key
#   apt_key:
#     url: https://nginx.org/keys/nginx_signing.key
#     state: present
#     keyring: /usr/share/keyrings/nginx-archive-keyring.gpg

# - name: download nginx repo
#   apt_repository:
#     repo: deb http://nginx.org/packages/ubuntu `lsb_release -cs` nginx"
#     state: present
#     filename: download_nginx_org_linux_ubuntu

- name: apt install nginx
  apt:
    name:
      - nginx
    state: present
    update_cache: yes
  register: install_nginx

- name: start nginx service
  service:
    name: nginx
    state: started